version: "3"

services:
  postgres:
    image: postgres:13-alpine
    env_file:
      - .env
    restart: unless-stopped

  rest-api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file:
      - .env
    ports:
      - $REST_API_PORT:$REST_API_PORT
    restart: unless-stopped
    depends_on:
      - postgres
