version: "3"

services:
  postgres:
    image: postgres:13-alpine
    env_file:
      - .env
    restart: unless-stopped

  rest-api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file:
      - .env
    ports:
      - $REST_API_PORT:$REST_API_PORT
    volumes:
      - ./tools:/tools:ro
    command: >
      sh -c "/tools/wait-for-it/wait-for-it.sh $POSTGRES_HOST:$POSTGRES_PORT -t 0 &&
             ./rest-api"
    restart: unless-stopped
    depends_on:
      - postgres
